/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LicenseNFT } from "./LicenseNFT";
export type { LicensingRoyalty } from "./LicensingRoyalty";
export type { OwnershipRegistry } from "./OwnershipRegistry";
