/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LicensingRoyalty__factory } from "./LicensingRoyalty__factory";
export { OwnershipRegistry__factory } from "./OwnershipRegistry__factory";
