/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LicensingRoyalty } from "./LicensingRoyalty";
export type { OwnershipRegistry } from "./OwnershipRegistry";
export * as factories from "./factories";
export { LicensingRoyalty__factory } from "./factories/LicensingRoyalty__factory";
export { OwnershipRegistry__factory } from "./factories/OwnershipRegistry__factory";
