/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LicensingRoyaltyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "companyAddress"
      | "companyBps"
      | "fund"
      | "funded"
      | "priceWei"
      | "release"
      | "released"
      | "studentAddress"
      | "studentBps"
      | "universityAddress"
      | "universityBps"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Funded" | "Released"): EventFragment;

  encodeFunctionData(
    functionFragment: "companyAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "companyBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(functionFragment: "funded", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceWei", values?: undefined): string;
  encodeFunctionData(functionFragment: "release", values?: undefined): string;
  encodeFunctionData(functionFragment: "released", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "studentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "studentBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "universityAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "universityBps",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "companyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "companyBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "funded", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceWei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "released", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "studentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "studentBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "universityAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "universityBps",
    data: BytesLike
  ): Result;
}

export namespace FundedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    studentAmount: BigNumberish,
    universityAmount: BigNumberish,
    companyAmount: BigNumberish
  ];
  export type OutputTuple = [
    studentAmount: bigint,
    universityAmount: bigint,
    companyAmount: bigint
  ];
  export interface OutputObject {
    studentAmount: bigint;
    universityAmount: bigint;
    companyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LicensingRoyalty extends BaseContract {
  connect(runner?: ContractRunner | null): LicensingRoyalty;
  waitForDeployment(): Promise<this>;

  interface: LicensingRoyaltyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  companyAddress: TypedContractMethod<[], [string], "view">;

  companyBps: TypedContractMethod<[], [bigint], "view">;

  fund: TypedContractMethod<[], [void], "payable">;

  funded: TypedContractMethod<[], [boolean], "view">;

  priceWei: TypedContractMethod<[], [bigint], "view">;

  release: TypedContractMethod<[], [void], "nonpayable">;

  released: TypedContractMethod<[], [boolean], "view">;

  studentAddress: TypedContractMethod<[], [string], "view">;

  studentBps: TypedContractMethod<[], [bigint], "view">;

  universityAddress: TypedContractMethod<[], [string], "view">;

  universityBps: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "companyAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "companyBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "funded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceWei"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "released"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "studentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "studentBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "universityAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "universityBps"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "Funded(address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "Released(uint256,uint256,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
